### ISSUE TITLE
MSharp.exe produced an error in Intellisense VSIX.

### ISSUE THREAD

**Issue by pharzath** [Geeksltd/MSharp.Docs#42]
It seems there is a problem when calling msharp.exe with this parameters from Msharp.Intellisense VSIX:
_msharp.exe  /intellisense /ExpectsCSharpStatement /file:"C:\Geeks\OneClick\M#\UI\Modules\-Custom\Header.cs" /setting:Code /line:39 /text:"public MvcHtmlString GetApplicableMenu(User user, HtmlHelper Html){\r\n            if (user is VendorManager)\r\n                return \r\nHtml.Action<Controllers.VendorMenuController>();\r\n            return null;\r\n            }"_

Error message returned by Msharp.exe :

> External command failed: 'C:\Geeks\OneClick\M#\lib\msharp.exe':
> Running > msharp /intellisense /ExpectsCSharpStatement /file:C:\Geeks\OneClick\M#\UI\Modules\-Custom\Header.cs /setting:Code /line:39 /text:public MvcHtmlString GetApplicableMenu(User user, HtmlHelper Html){
>             if (user is VendorManager)
>                 return Html.Action<Controllers.VendorMenuController>();
>             return null;
>             }
> 
> C:\Geeks\OneClick
> Loading project...-------------------
>    at System.MSharpExtensions.To(String text, Type targetType)
>    at System.MSharpExtensions.To[T](String text)
>    at MSharp.MCSharpLoader.LoadXml()
>    at MSharp.MCSharpLoader..ctor(DirectoryInfo solutionFolder)
>    at MSharp.Program.LoadProject()
>    at MSharp.Program.Process()
>    at MSharp.Program.Main(String[] args)
> -------------------
## Could not convert "Error: File not found: C:\Geeks\OneClick\M#\lib\#Model.dll
> -------------------
>    at MSharp.Program.GetAssembly(String name)
>    at MSharp.Program.Main(String[] args)
> " to type System.Xml.Linq.XElement.
> Base issue: Data at the root level is invalid. Line 1, position 1.

**Comment by pharzath** [comment]
maybe it search's in incorrect path :
C:\Geeks\OneClick\M#\lib#Model.dll  -> it should be : C:\Geeks\OneClick\M#\lib\\#Model.dll
So it needs a "\\" after lib folder

**Comment by pharzath** [comment]
Solved
